let a=10;
let b=20;
let sum=a+b;
console.log("The sum of a and b is: "+sum);
console.log("Hello, World!");
console.log("This is a simple JavaScript program.");
console.log("The value of a is: "+a);
console.log("The value of b is: "+b);
console.log("End of the program.");
console.log("Goodbye!");